openapi: "3.0.0"
info:
  version: "v0.2.10"
  title: MixerAPI Demo (Public API)
  description: |
    Check out [MixerAPI.com](https://mixerapi.com) to streamline your API development.

    You can view the source code for this [demo here](https://github.com/mixerapi/demo).

    If you are viewing this on demo.mixerapi.com then the database resets every 24 hours.

    Browse the [JSON-LD vocabulary](/public/vocab) for this API.

    Go back to the [homepage](/).

  license:
    name: MIT

paths:


components:
  schemas:
    Exception:
      type: object
      properties:
        code:
          type: integer
          example: 500
        url:
          type: string
          example: /url/path
        message:
          type: string
          example: Internal Error
      xml:
        name: response
x-mixerapi-demo:
  components:
    schemas:
      FilmByRating:
        type: object
        properties:
          rating:
            type: string
            example: PG
          total:
            type: integer
            example: 100
      ActorFilm:
        type: object
        properties:
          id:
            type: string
            example: "9d90c3bc-8433-11ea-82ad-2079182842a9"
          actor_id:
            type: integer
            example: 21
          film_id:
            type: integer
            example: 117
          film:
            type: object
            $ref: '#/components/schemas/Film'
      FilmActor:
        type: object
        properties:
          id:
            type: string
            example: "9d90c3bc-8433-11ea-82ad-2079182842a9"
          actor_id:
            type: integer
            example: 21
          film_id:
            type: integer
            example: 117
          film:
            type: object
            $ref: '#/components/schemas/Actor'

